version: '3.8'
services:
    postgresql:
        image: postgres:13
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: job_nest
            POSTGRES_PASSWORD: job_nest
            POSTGRES_DB: job_nest
        volumes:
            - postgresql:/var/lib/postgresql/data
volumes:
    postgresql: {}
